/// Flutter icons Aquaproicon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Aquaproicon
///      fonts:
///       - asset: fonts/Aquaproicon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Aquaproicon {
  Aquaproicon._();

  static const _kFontFam = 'Aquaproicon';
  static const _kFontPkg = null;

  static const IconData iconfinder_hand_cleaning = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconfinder_dishes_hand_wash = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
